
version: 2.1
jobs:
   sachin:
    steps:
     - run: echo '"Hellow Sachin"

   soham:
    steps: 
     - run: echo '"Hellow Soham"


workflows:
  version: 2.1
  sachin_soham:
    jobs:
     - sachin
     - soham
    