
# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  sachin: circleci/welcome-orb@0.4.1
  soham: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  sachin:
   # Run the welcome/run job in its own container
    jobs:
     - sachin/run
     -soham/run
  
     